package com.breakinblocks.neovitae.datagen.provider;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.DataMapProvider;
import com.breakinblocks.neovitae.datagen.content.datamap.AltarRuneStatsData;
import com.breakinblocks.neovitae.datagen.content.datamap.DungeonOreWeightsData;
import com.breakinblocks.neovitae.datagen.content.datamap.BloodOrbStats;
import com.breakinblocks.neovitae.datagen.content.datamap.EntitySacrificeData;
import com.breakinblocks.neovitae.datagen.content.datamap.SpiritusGemMax;
import com.breakinblocks.neovitae.datagen.content.datamap.TranquilityData;
import com.breakinblocks.neovitae.datagen.content.datamap.RoutingNodeStatsData;

import java.util.concurrent.CompletableFuture;

public class NVDataMapProvider extends DataMapProvider {
    public NVDataMapProvider(PackOutput packOutput, CompletableFuture<HolderLookup.Provider> lookupProvider) {
        super(packOutput, lookupProvider);
    }

    @Override
    protected void gather(HolderLookup.Provider provider) {
        SpiritusGemMax.bootstrap(this::builder);
        BloodOrbStats.bootstrap(this::builder);
        AltarRuneStatsData.bootstrap(this::builder);
        EntitySacrificeData.bootstrap(this::builder);
        TranquilityData.bootstrap(this::builder);
        RoutingNodeStatsData.bootstrap(this::builder);
        DungeonOreWeightsData.bootstrap(this::builder);
        // SigilStatsData is now generated by SigilStatsProvider as individual files
        // RitualStatsData is now generated by RitualStatsProvider as individual files
    }
}
